//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenosisBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Msg
    {
        public string Id { get; set; }
        public string Text { get; set; }
        public System.DateTime Time { get; set; }
        public string PoolId { get; set; }
        public string UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Pool Pool { get; set; }
    }
}
